version: "3"

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf #:1.5.3
    container_name: telegraf
    restart: always
    hostname: my-telegraf
    #    networks:
    #      - monitoring
    volumes:
      - telegraf-volume:/var/lib/telegraf
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    links:
      - influxdb
    depends_on:
      - influxdb
    ports:
      - "8125:8125/udp"
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc

  # Define an InfluxDB service
  influxdb:
    image: influxdb #:1.5.1
    container_name: influxdb
    restart: always
    #    networks:
    #      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
    ports:
      - "8086:8086"

  # Define a Chronograf service
  chronograf:
    image: chronograf #:1.4.3.1
    container_name: chronograf
    restart: always
    #    networks:
    #      - monitoring
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
    volumes:
      - chronograf-volume:/var/lib/chronograf
    depends_on:
      - influxdb
      - kapacitor

  # Define a Kapacitor service
  kapacitor:
    image: kapacitor #:1.4.1
    container_name: kapacitor
    restart: always
    #    networks:
    #      - monitoring
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
    volumes:
      - kapacitor-volume:/var/lib/kapacitor

  # Define a Grafana service
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    #    networks:
    #      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana

#networks:
#  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
  telegraf-volume:
    external: true
  chronograf-volume:
    external: true
  kapacitor-volume:
    external: true

