server:
  port: 8080
spring:
  application:
    name: metric-sample
  datasource:
    url:  jdbc:h2:mem:sample-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  main:
    allow-bean-definition-overriding: true
management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  metrics:
    binders:
      hystrix:
        enabled: true
