server:
  port: 8080
spring:
  application:
    name: metric-sample
  datasource:
    url:  jdbc:h2:mem:sample-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        generate_statistics: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    web:
      server:
        auto-time-requests: true
    binders:
      hystrix:
        enabled: true
    export:
      statsd:
        enabled: true
        flavor: telegraf
        port: 8125
        host: 127.0.0.1
    tags:
      region: us-east-1
      stack: prod
